### ISSUE TITLE
ffprobe and avprobe not found in $PATH

### ISSUE THREAD

**Issue by aston314** [MrKsey/torrserver#6]
ffprobe and avprobe not found in $PATH

What is mean?

**Comment by MrKsey** [comment]
> ffprobe and avprobe not found in $PATH
> 
> What is mean?

The ffprobe utility is missing.
I don't know why TorrServer needs it. It is part of the ffmpeg package.
The ffmpeg package is very large, so I didn't include it in the image.
I have now fixed this and included the static version of the ffprobe utility instead of the whole ffmpeg package.
You need to delete the current container and image and start the new container.
Problem fixed.
